import { StyleSheet } from "react-native";
import Colors from "../../utils/colors";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BACKGROUND_GREEN,
  },
  headerLogin: {
    flex: 1,
    justifyContent: "flex-end",
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  titleHeader: {
    fontSize: 30,
    fontWeight: "500",
    color: Colors.white,
  },
  viewLanguages: {
    marginTop: 5,
    position: "absolute",
    right: 10,
    top: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  textSelectLang: {
    fontSize: 13,
    color: "white",
    fontWeight: "600",
    marginLeft: 5,
  },
  textTitleBody: {
    fontSize: 14,
    color: "white",
    fontWeight: "normal",
  },
  viewTextInput: {
    marginVertical: 10,
    paddingHorizontal: 20,
  },
  inputView: {
    flexDirection: "row",
    // paddingVertical: 5,
    paddingHorizontal: 10,
    borderBottomColor: "gray",
    borderBottomWidth: 0.5,
    justifyContent: "center",
    alignItems: "center",
  },
  textInput: {
    flex: 1,
    paddingLeft: 10,
    color: "white",
    fontSize: 13,
    fontWeight: "normal",
    paddingVertical: 10,
  },
  bodyView: {
    flex: 3,
    backgroundColor: Colors.PURPLE_COAL,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingVertical: 30,
  },
  errorMsg: {
    color: Colors.RED,
    fontSize: 13,
    paddingLeft: 20,
  },
  textButton: {
    color: "white",
    fontWeight: "600",
    fontSize: 18,
    marginHorizontal: 20,
  },
  viewButtonLogin: {
    marginTop: 20,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    marginHorizontal: 20,

    borderRadius: 4,
    borderColor: "gray",
    borderWidth: 1,
    backgroundColor: Colors.BLUE,
  },
  viewButtonSign: {
    marginHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    borderColor: "gray",
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: Colors.ORANGE,
  },
  imgBottom: {
    width: "100%",
    bottom: 0,
    position: "absolute",
    zIndex: -1,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    width: "70%",
    backgroundColor: "white",
    borderRadius: 10,
  },
  headerModal: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 30,
  },
  textTile: {
    fontSize: 20,
    fontWeight: "500",
    color: "black",
  },
  textContent: {
    textAlign: "center",
    marginTop: 5,
    fontSize: 16,
    color: "black",
  },
  viewBorder: {
    backgroundColor: "gray",
    height: 0.19,
  },
  viewButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
  },
  textButtons: {
    fontSize: 20,
    color: "rgb(55,121,246)",
  },
  textOr: {
    fontSize: 12,
    color: Colors.white,
    textAlign: "center",
    fontWeight: "600",
    paddingVertical: 5,
  },
  viewButtonLoginFb: {
    backgroundColor: Colors.gray_5,
    marginHorizontal: 20,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 5,
    borderColor: "gray",
    borderWidth: 1,
  },
  viewButtonLoginGoogle: {
    backgroundColor: Colors.gray_5,
    marginHorizontal: 20,
    marginVertical:10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 5,
    borderColor: "gray",
    borderWidth: 1,
  },
});

export default styles;
